// ─────────────────────────────────────────────
// Shared mock data for Product Listing + Compare pages
// ─────────────────────────────────────────────

export interface Product {
  id: string
  name: string
  description?: string
  image?: string
  buyHref?: string
  learnMoreHref?: string
  // Listing page filters
  category?: string
  size?: string
  resolution?: string
  refreshRate?: string
  panelType?: string
  // Compare page specs
  specs: Record<string, string>
}

export const MOCK_PRODUCTS: Product[] = [
  {
    id: '1',
    name: 'VA2406-H',
    image: 'https://www.viewsonic.com/vsAssetFile/global/img/resize/slides/_lcd_display_%28new%29/VA2406-MH/scaled/GPG-23-MON-VA2406-MH-Product%20Photo_F01_pc_m.webp',
    description: '24" Full HD Monitor with Dual, 2W speakers and 100Hz',
    category: 'home', size: '24', resolution: '1920x1080', refreshRate: '100hz', panelType: 'va',
    specs: {
      'Display Size (in.)': '24', 'Viewable Area (in.)': '23.8', 'Panel Type': 'VA Technology',
      'Resolution': '1920 x 1080', 'Resolution Type': 'FHD (Full HD)', 'Static Contrast Ratio': '4,000:1 (typ)',
      'Dynamic Contrast Ratio': '50M:1', 'Brightness': '250 cd/m² (typ)', 'Light Source': 'LED',
      'Color Space Support': '8 bit true', 'Viewing Angles': '178° horizontal, 178° vertical',
      'Backlight Life (Hours)': '30000 Hrs (Min)', 'Curvature': 'Flat', 'Refresh Rate (Hz)': '100',
      'Variable Refresh Rate Technology': 'Yes', 'Low Blue Light': 'Software solution',
      'Flicker-Free': 'Yes', 'Color Gamut': 'NTSC: 72% size (Typ)',
      'PC Resolution (max)': '1920x1080', 'Mac® Resolution (max)': '1920x1080',
      'PC Operating System': 'Windows 10/11 certified; macOS tested', 'Mac® Resolution (min)': '1920x1080',
      'Internal Speakers': '0.8Watts x2', 'VGA': '1x', 'HDMI': '1x', 'DisplayPort': '-',
      'USB Type-C': '-', 'Audio In/Out': 'Audio in', 'Power Consumption (typical)': '17W',
      'Standby Power': '< 0.5W', 'Power Input': '100-240V, 50/60Hz',
    },
  },
  {
    id: '2',
    name: 'VA242-H',
    image: 'https://www.viewsonic.com/vsAssetFile/global/img/resize/slides/_lcd_display_%28new%29/VA242-H/scaled/GPG-25-MON-VA242-H-Product%20Photo_F01_pc_m.webp',
    description: '24" Full HD IPS Monitor with Fast 1ms Response Time',
    category: 'home', size: '24', resolution: '1920x1080', refreshRate: '100hz', panelType: 'ips',
    specs: {
      'Display Size (in.)': '24', 'Viewable Area (in.)': '23.8', 'Panel Type': 'IPS Technology',
      'Resolution': '1920 x 1080', 'Resolution Type': 'FHD (Full HD)', 'Static Contrast Ratio': '1,000:1 (typ)',
      'Dynamic Contrast Ratio': '80M:1', 'Brightness': '300 cd/m² (typ)', 'Light Source': 'LED',
      'Color Space Support': '8 bit (6 bit + FRC)', 'Viewing Angles': '178° horizontal, 178° vertical',
      'Backlight Life (Hours)': '30000 Hrs (Min)', 'Curvature': 'Flat', 'Refresh Rate (Hz)': '100',
      'Variable Refresh Rate Technology': 'Yes', 'Low Blue Light': 'Software solution',
      'Flicker-Free': 'Yes', 'Color Gamut': 'NTSC: 80% size (Typ)',
      'PC Resolution (max)': '1920x1080', 'Mac® Resolution (max)': '1920x1080',
      'PC Operating System': 'Windows 10/11 certified; macOS tested', 'Mac® Resolution (min)': '1920x1080',
      'Internal Speakers': '0.8Watts x2', 'VGA': '-', 'HDMI': '2x', 'DisplayPort': '1x',
      'USB Type-C': '-', 'Audio In/Out': 'Audio in', 'Power Consumption (typical)': '18W',
      'Standby Power': '< 0.5W', 'Power Input': '100-240V, 50/60Hz',
    },
  },
  {
    id: '3',
    name: 'VA242-MHD',
    image: 'https://www.viewsonic.com/vsAssetFile/global/img/resize/slides/_lcd_display_%28new%29/VA242-MHD/scaled/GPG-25-MON-VA242-MHD-Product%20Photo_F01_pc_m.webp',
    description: '24" Full HD IPS Monitor with Fast 1ms Response Time',
    category: 'home', size: '24', resolution: '1920x1080', refreshRate: '100hz', panelType: 'ips',
    specs: {
      'Display Size (in.)': '24', 'Viewable Area (in.)': '23.8', 'Panel Type': 'IPS Technology',
      'Resolution': '1920 x 1080', 'Resolution Type': 'FHD (Full HD)', 'Static Contrast Ratio': '1,000:1 (typ)',
      'Dynamic Contrast Ratio': '80M:1', 'Brightness': '300 cd/m² (typ)', 'Light Source': 'LED',
      'Color Space Support': '8 bit (6 bit + FRC)', 'Viewing Angles': '178° horizontal, 178° vertical',
      'Backlight Life (Hours)': '30000 Hrs (Min)', 'Curvature': 'Flat', 'Refresh Rate (Hz)': '100',
      'Variable Refresh Rate Technology': 'Yes', 'Low Blue Light': 'Software solution',
      'Flicker-Free': 'Yes', 'Color Gamut': 'NTSC: 80% size (Typ)',
      'PC Resolution (max)': '3840 x 1280', 'Mac® Resolution (max)': '3840 x 1280',
      'PC Operating System': 'Windows 10/11 certified; macOS tested', 'Mac® Resolution (min)': '1920x1080',
      'Internal Speakers': '0.8Watts x2', 'VGA': '-', 'HDMI': '2x', 'DisplayPort': '1x',
      'USB Type-C': '-', 'Audio In/Out': 'Audio in/out', 'Power Consumption (typical)': '19W',
      'Standby Power': '< 0.5W', 'Power Input': '100-240V, 50/60Hz',
    },
  },
  {
    id: '4',
    name: 'VA272-H',
    image: 'https://www.viewsonic.com/vsAssetFile/global/img/resize/slides/_lcd_display_%28new%29/VA272-H/scaled/GPG-25-MON-VA272-H-Product%20Photo_F01_pc_m.webp',
    description: '27" Full HD+100Hz Monitor with Dual 2W speakers',
    category: 'home', size: '27', resolution: '1920x1080', refreshRate: '100hz', panelType: 'va',
    specs: {
      'Display Size (in.)': '27', 'Viewable Area (in.)': '26.9', 'Panel Type': 'VA Technology',
      'Resolution': '1920 x 1080', 'Resolution Type': 'FHD (Full HD)', 'Static Contrast Ratio': '4,000:1 (typ)',
      'Dynamic Contrast Ratio': '50M:1', 'Brightness': '250 cd/m² (typ)', 'Light Source': 'LED',
      'Color Space Support': '8 bit true', 'Viewing Angles': '178° horizontal, 178° vertical',
      'Backlight Life (Hours)': '30000 Hrs (Min)', 'Curvature': 'Flat', 'Refresh Rate (Hz)': '100',
      'Variable Refresh Rate Technology': 'Yes', 'Low Blue Light': 'Software solution',
      'Flicker-Free': 'Yes', 'Color Gamut': 'NTSC: 72% size (Typ)',
      'PC Resolution (max)': '1920x1080', 'Mac® Resolution (max)': '1920x1080',
      'PC Operating System': 'Windows 10/11 certified; macOS tested', 'Mac® Resolution (min)': '1920x1080',
      'Internal Speakers': '0.8Watts x2', 'VGA': '1x', 'HDMI': '2x', 'DisplayPort': '-',
      'USB Type-C': '-', 'Audio In/Out': 'Audio in', 'Power Consumption (typical)': '22W',
      'Standby Power': '< 0.5W', 'Power Input': '100-240V, 50/60Hz',
    },
  },
  {
    id: '5',
    name: 'VA272-HDJ',
    image: 'https://www.viewsonic.com/vsAssetFile/global/img/resize/slides/_lcd_display_%28new%29/VA272-HDJ/scaled/GPG-25-MON-VA272-HDJ-Product%20Photo_F01_pc_m.webp',
    description: '27" Full HD+100Hz Ergonomic Monitor with Fast 1ms Response',
    category: 'professional', size: '27', resolution: '1920x1080', refreshRate: '100hz', panelType: 'ips',
    specs: {
      'Display Size (in.)': '27', 'Viewable Area (in.)': '26.9', 'Panel Type': 'IPS Technology',
      'Resolution': '1920 x 1080', 'Resolution Type': 'FHD (Full HD)', 'Static Contrast Ratio': '1,000:1 (typ)',
      'Dynamic Contrast Ratio': '80M:1', 'Brightness': '300 cd/m² (typ)', 'Light Source': 'LED',
      'Color Space Support': '8 bit (6 bit + FRC)', 'Viewing Angles': '178° horizontal, 178° vertical',
      'Backlight Life (Hours)': '30000 Hrs (Min)', 'Curvature': 'Flat', 'Refresh Rate (Hz)': '100',
      'Variable Refresh Rate Technology': 'Yes', 'Low Blue Light': 'Software solution',
      'Flicker-Free': 'Yes', 'Color Gamut': 'NTSC: 80% size (Typ)',
      'PC Resolution (max)': '1920x1080', 'Mac® Resolution (max)': '1920x1080',
      'PC Operating System': 'Windows 10/11 certified; macOS tested', 'Mac® Resolution (min)': '1920x1080',
      'Internal Speakers': '-', 'VGA': '-', 'HDMI': '2x', 'DisplayPort': '1x',
      'USB Type-C': '-', 'Audio In/Out': 'Audio in', 'Power Consumption (typical)': '23W',
      'Standby Power': '< 0.5W', 'Power Input': '100-240V, 50/60Hz',
    },
  },
  {
    id: '6',
    name: 'VA272-MHD',
    image: 'https://www.viewsonic.com/vsAssetFile/global/img/resize/slides/_lcd_display_%28new%29/VA272-MHD/scaled/GPG-25-MON-VA272-MHD-Product%20Photo_F01_pc_m.webp',
    description: '27" Full HD+100Hz Ergonomic Monitor with Fast 1ms Response',
    category: 'professional', size: '27', resolution: '1920x1080', refreshRate: '100hz', panelType: 'ips',
    specs: {
      'Display Size (in.)': '27', 'Viewable Area (in.)': '26.9', 'Panel Type': 'IPS Technology',
      'Resolution': '1920 x 1080', 'Resolution Type': 'FHD (Full HD)', 'Static Contrast Ratio': '1,000:1 (typ)',
      'Dynamic Contrast Ratio': '80M:1', 'Brightness': '300 cd/m² (typ)', 'Light Source': 'LED',
      'Color Space Support': '8 bit (6 bit + FRC)', 'Viewing Angles': '178° horizontal, 178° vertical',
      'Backlight Life (Hours)': '30000 Hrs (Min)', 'Curvature': 'Flat', 'Refresh Rate (Hz)': '100',
      'Variable Refresh Rate Technology': 'Yes', 'Low Blue Light': 'Software solution',
      'Flicker-Free': 'Yes', 'Color Gamut': 'NTSC: 80% size (Typ)',
      'PC Resolution (max)': '1920x1080', 'Mac® Resolution (max)': '1920x1080',
      'PC Operating System': 'Windows 10/11 certified; macOS tested', 'Mac® Resolution (min)': '1920x1080',
      'Internal Speakers': '0.8Watts x2', 'VGA': '-', 'HDMI': '2x', 'DisplayPort': '1x',
      'USB Type-C': '-', 'Audio In/Out': 'Audio in/out', 'Power Consumption (typical)': '24W',
      'Standby Power': '< 0.5W', 'Power Input': '100-240V, 50/60Hz',
    },
  },
  {
    id: '7',
    name: 'VA3420C-2',
    image: 'https://www.viewsonic.com/vsAssetFile/global/img/resize/slides/_lcd_display_%28new%29/VA272-MHD/scaled/GPG-25-MON-VA272-MHD-Product%20Photo_F01_pc_m.webp',
    description: '24" QHD Curved Monitor with KVM Switch',
    category: 'gaming', size: '24', resolution: '2560x1440', refreshRate: '100hz', panelType: 'va',
    specs: {
      'Display Size (in.)': '24', 'Viewable Area (in.)': '23.6', 'Panel Type': 'VA Technology',
      'Resolution': '2560 x 1440', 'Resolution Type': 'QHD', 'Static Contrast Ratio': '3,000:1 (typ)',
      'Dynamic Contrast Ratio': '50M:1', 'Brightness': '250 cd/m² (typ)', 'Light Source': 'LED',
      'Color Space Support': '8 bit true', 'Viewing Angles': '178° horizontal, 178° vertical',
      'Backlight Life (Hours)': '30000 Hrs (Min)', 'Curvature': '1500R', 'Refresh Rate (Hz)': '100',
      'Variable Refresh Rate Technology': 'Yes (AMD FreeSync)', 'Low Blue Light': 'Hardware solution',
      'Flicker-Free': 'Yes', 'Color Gamut': 'NTSC: 90% size (Typ)',
      'PC Resolution (max)': '2560x1440', 'Mac® Resolution (max)': '2560x1440',
      'PC Operating System': 'Windows 10/11 certified; macOS tested', 'Mac® Resolution (min)': '1920x1080',
      'Internal Speakers': '2Watts x2', 'VGA': '-', 'HDMI': '2x', 'DisplayPort': '1x',
      'USB Type-C': '1x', 'Audio In/Out': 'Audio out', 'Power Consumption (typical)': '28W',
      'Standby Power': '< 0.5W', 'Power Input': '100-240V, 50/60Hz',
    },
  },
  {
    id: '8',
    name: 'VA3456-mhdj',
    image: 'https://www.viewsonic.com/vsAssetFile/global/img/resize/slides/_lcd_display_%28new%29/VA3456-MHDJ/scaled/GPG-23-MON-VA3456-mhdj-Product%20Photo_F01_pc_m.webp',
    description: '34" 1440p Ultra-Wide IPS Monitor',
    category: 'professional', size: '32', resolution: '3840x2160', refreshRate: '60hz', panelType: 'ips',
    specs: {
      'Display Size (in.)': '34', 'Viewable Area (in.)': '33.6', 'Panel Type': 'IPS Technology',
      'Resolution': '3440 x 1440', 'Resolution Type': 'UWQHD', 'Static Contrast Ratio': '1,000:1 (typ)',
      'Dynamic Contrast Ratio': '80M:1', 'Brightness': '300 cd/m² (typ)', 'Light Source': 'LED',
      'Color Space Support': '8 bit true', 'Viewing Angles': '178° horizontal, 178° vertical',
      'Backlight Life (Hours)': '30000 Hrs (Min)', 'Curvature': 'Flat', 'Refresh Rate (Hz)': '60',
      'Variable Refresh Rate Technology': '-', 'Low Blue Light': 'Software solution',
      'Flicker-Free': 'Yes', 'Color Gamut': 'NTSC: 72% size (Typ)',
      'PC Resolution (max)': '3440x1440', 'Mac® Resolution (max)': '3440x1440',
      'PC Operating System': 'Windows 10/11 certified; macOS tested', 'Mac® Resolution (min)': '1920x1080',
      'Internal Speakers': '2Watts x2', 'VGA': '-', 'HDMI': '2x', 'DisplayPort': '1x',
      'USB Type-C': '1x', 'Audio In/Out': 'Audio in/out', 'Power Consumption (typical)': '35W',
      'Standby Power': '< 0.5W', 'Power Input': '100-240V, 50/60Hz',
    },
  },
  {
    id: '9',
    name: 'VA1655',
    description: '16" Lightweight Portable Monitor',
    image: 'https://www.viewsonic.com/vsAssetFile/global/img/resize/slides/_lcd_display_%28new%29/VA1655/scaled/VA1655_F01_pc_m.webp',
    category: 'portable', size: '17', resolution: '1920x1080', refreshRate: '60hz', panelType: 'ips',
    specs: {
      'Display Size (in.)': '15.6', 'Viewable Area (in.)': '15.4', 'Panel Type': 'IPS Technology',
      'Resolution': '1920 x 1080', 'Resolution Type': 'FHD (Full HD)', 'Static Contrast Ratio': '700:1 (typ)',
      'Dynamic Contrast Ratio': '50M:1', 'Brightness': '250 cd/m² (typ)', 'Light Source': 'LED',
      'Color Space Support': '8 bit (6 bit + FRC)', 'Viewing Angles': '170° horizontal, 160° vertical',
      'Backlight Life (Hours)': '30000 Hrs (Min)', 'Curvature': 'Flat', 'Refresh Rate (Hz)': '60',
      'Variable Refresh Rate Technology': '-', 'Low Blue Light': 'Software solution',
      'Flicker-Free': 'Yes', 'Color Gamut': 'NTSC: 72% size (Typ)',
      'PC Resolution (max)': '1920x1080', 'Mac® Resolution (max)': '1920x1080',
      'PC Operating System': 'Windows 10/11 certified; macOS tested', 'Mac® Resolution (min)': '1920x1080',
      'Internal Speakers': '1Watt x2', 'VGA': '-', 'HDMI': '-', 'DisplayPort': '-',
      'USB Type-C': '2x', 'Audio In/Out': 'Audio out', 'Power Consumption (typical)': '10W',
      'Standby Power': '< 0.5W', 'Power Input': '5V/3A (USB-C)',
    },
  },
  {
    id: '10',
    name: 'VA1650',
    image: 'https://www.viewsonic.com/vsAssetFile/global/img/resize/slides/_lcd_display_%28new%29/VA1650/scaled/GPG-25-MON-VA1650-Product%20Photo_F01_pc_m.webp',
    description: '16" Full-HD Lightweight Portable Monitor',
    category: 'portable', size: '17', resolution: '1920x1080', refreshRate: '60hz', panelType: 'ips',
    specs: {
      'Display Size (in.)': '15.6', 'Viewable Area (in.)': '15.4', 'Panel Type': 'IPS Technology',
      'Resolution': '1920 x 1080', 'Resolution Type': 'FHD (Full HD)', 'Static Contrast Ratio': '700:1 (typ)',
      'Dynamic Contrast Ratio': '50M:1', 'Brightness': '300 cd/m² (typ)', 'Light Source': 'LED',
      'Color Space Support': '8 bit true', 'Viewing Angles': '170° horizontal, 160° vertical',
      'Backlight Life (Hours)': '30000 Hrs (Min)', 'Curvature': 'Flat', 'Refresh Rate (Hz)': '60',
      'Variable Refresh Rate Technology': '-', 'Low Blue Light': 'Software solution',
      'Flicker-Free': 'Yes', 'Color Gamut': 'NTSC: 45% size (Typ)',
      'PC Resolution (max)': '1920x1080', 'Mac® Resolution (max)': '1920x1080',
      'PC Operating System': 'Windows 10/11 certified; macOS tested', 'Mac® Resolution (min)': '1920x1080',
      'Internal Speakers': '1Watt x2', 'VGA': '-', 'HDMI': 'Micro HDMI x1', 'DisplayPort': '-',
      'USB Type-C': '1x', 'Audio In/Out': 'Audio out', 'Power Consumption (typical)': '9W',
      'Standby Power': '< 0.5W', 'Power Input': '5V/2A (USB-C)',
    },
  },
  {
    id: '11',
    name: 'VA1653',
    image: 'https://www.viewsonic.com/vsAssetFile/global/img/resize/slides/_lcd_display_%28new%29/VA1653-1T/scaled/GPG-25-MON-VA1653-Product%20Photo_F01_pc_m.webp',
    description: '16" Full-HD c-glass-right Monitor',
    category: 'portable', size: '17', resolution: '1920x1080', refreshRate: '60hz', panelType: 'ips',
    specs: {
      'Display Size (in.)': '15.6', 'Viewable Area (in.)': '15.4', 'Panel Type': 'IPS Technology',
      'Resolution': '1920 x 1080', 'Resolution Type': 'FHD (Full HD)', 'Static Contrast Ratio': '700:1 (typ)',
      'Dynamic Contrast Ratio': '50M:1', 'Brightness': '250 cd/m² (typ)', 'Light Source': 'LED',
      'Color Space Support': '8 bit (6 bit + FRC)', 'Viewing Angles': '170° horizontal, 160° vertical',
      'Backlight Life (Hours)': '30000 Hrs (Min)', 'Curvature': 'Flat', 'Refresh Rate (Hz)': '60',
      'Variable Refresh Rate Technology': '-', 'Low Blue Light': 'Software solution',
      'Flicker-Free': 'Yes', 'Color Gamut': 'NTSC: 45% size (Typ)',
      'PC Resolution (max)': '1920x1080', 'Mac® Resolution (max)': '1920x1080',
      'PC Operating System': 'Windows 10/11 certified; macOS tested', 'Mac® Resolution (min)': '1920x1080',
      'Internal Speakers': '-', 'VGA': '-', 'HDMI': '-', 'DisplayPort': '-',
      'USB Type-C': '1x', 'Audio In/Out': '-', 'Power Consumption (typical)': '8W',
      'Standby Power': '< 0.5W', 'Power Input': '5V/2A (USB-C)',
    },
  },
  {
    id: '12',
    name: 'VA709',
    image: 'https://www.viewsonic.com/vsAssetFile/global/img/resize/slides/_lcd_display_%28new%29/VA709/scaled/GPG-24-MON-VA709-Product%20Photo_F01_pc_m.webp',
    description: '17" Home and Office Monitor',
    category: 'home', size: '17', resolution: '1920x1080', refreshRate: '60hz', panelType: 'tn',
    specs: {
      'Display Size (in.)': '17', 'Viewable Area (in.)': '16.9', 'Panel Type': 'TN Technology',
      'Resolution': '1280 x 1024', 'Resolution Type': 'SXGA', 'Static Contrast Ratio': '700:1 (typ)',
      'Dynamic Contrast Ratio': '50M:1', 'Brightness': '250 cd/m² (typ)', 'Light Source': 'LED',
      'Color Space Support': '6 bit', 'Viewing Angles': '170° horizontal, 160° vertical',
      'Backlight Life (Hours)': '30000 Hrs (Min)', 'Curvature': 'Flat', 'Refresh Rate (Hz)': '60',
      'Variable Refresh Rate Technology': '-', 'Low Blue Light': 'Software solution',
      'Flicker-Free': 'Yes', 'Color Gamut': 'NTSC: 72% size (Typ)',
      'PC Resolution (max)': '1280x1024', 'Mac® Resolution (max)': '1280x1024',
      'PC Operating System': 'Windows 10/11 certified', 'Mac® Resolution (min)': '800x600',
      'Internal Speakers': '-', 'VGA': '1x', 'HDMI': '-', 'DisplayPort': '-',
      'USB Type-C': '-', 'Audio In/Out': '-', 'Power Consumption (typical)': '14W',
      'Standby Power': '< 0.5W', 'Power Input': '100-240V, 50/60Hz',
    },
  },
]
